### ISSUE TITLE
Not rendering SVG Pattern elements

### ISSUE THREAD

**Issue by lucasbraum** [gojko/librsvg-static-lambda-binary#2]
I have an SVG file that contains a `<rect>` element with a `<pattern>` as fill. When I convert this file to PNG or PDF, this rect is not rendered.

Follow the SVG code:

`<svg viewBox="0 0 800 800" xmlns="http://www.w3.org/2000/svg" version="1.1" xmlns:xlink="http://www.w3.org/1999/xlink"  width="800" height="800">
	<rect width="100%" height="100%" fill="url(#Svgjs1018)" x="0" y="0" class=""></rect>
	<pattern x="0" y="0" width="32" height="26" patternUnits="userSpaceOnUse" id="Svgjs1018">
		<g>
			<rect x="0" class="pattern-background-rect" fill="#63c6ff" width="32" height="26"></rect>
			<g fill="#000000" fill-opacity="0.18">
				<path d="M12,0h2v4c0,3.9-3.1,7-7,7c-3.9,0-7-3.1-7-7V0h2v4c0,2.8,2.2,5,5,5c2.8,0,5-2.2,5-5V0z M7,13c-3.9,0-7,3.1-7,7v6h2v-6 c0-2.8,2.2-5,5-5c2.8,0,5,2.2,5,5v6h2v-6C14,16.1,10.9,13,7,13z M30,7v10c0,3.9-3.1,7-7,7c-3.9,0-7-3.1-7-7V7c0-3.9,3.1-7,7-7 C26.9,0,30,3.1,30,7z M28,7c0-2.8-2.2-5-5-5c-2.8,0-5,2.2-5,5v10c0,2.8,2.2,5,5,5c2.8,0,5-2.2,5-5V7z"></path>
			</g>
		</g>
	</pattern>
</svg>`

**Comment by gojko** [comment]
Hi, this is likely a bug to report upstram to rsvg, the repo you reported it to just contains a statically compiled binary for aws lambda.

**Comment by lucasbraum** [comment]
Apparently it has something to do with your compiled rsvg since in my MacBook it is working fine with Patterns (rsvg-convert version 2.40.17).

Probably it is because of the rsvg dependencies used to compile the binary (Cairo or other). I will try to find out exactly which dependency should be updated or is missing from AMI.

Ps. if you use an ec2 ubuntu image it works fine.

**Comment by gojko** [comment]
it's possible that librsvg-2.26.3 (the version compiled here) didn't support that yet also. lambda uses quite an outdated linux system, and it's impossible to install new system libraries, so the latest version that compiles successfully on the current AMIs is 2.26.

**Comment by lucasbraum** [comment]
Is there any chance for you to compile a new version of rsvg? 😄 
I am trying by myself but facing many troubles:

See my updated compile-static.sh file
[https://github.com/lucasbraum/rsvg-convert-aws-lambda-binary/blob/master/compile-static.sh](https://github.com/lucasbraum/rsvg-convert-aws-lambda-binary/blob/master/compile-static.sh)

I am receiving this error:
`checking for some Win32 platform... no
checking for native Win32... no
checking for 	gdk-pixbuf-2.0 >= 2.20 	glib-2.0 >= 2.12.0 	gio-2.0 >= 2.24.0 	libxml-2.0 >= 2.7.0 	pangocairo >= 1.32.6 	cairo >= 1.2.0 	cairo-png >= 1.2.0
        libcroco-0.6 >= 0.6.1... no
configure: error: Package requirements (	gdk-pixbuf-2.0 >= 2.20 	glib-2.0 >= 2.12.0 	gio-2.0 >= 2.24.0 	libxml-2.0 >= 2.7.0 	pangocairo >= 1.32.6 	cairo >= 1.2.0 	cairo-png >= 1.2.0
        libcroco-0.6 >= 0.6.1) were not met:

No package 'gdk-pixbuf-2.0' found
Requested 'pangocairo >= 1.32.6' but version of Pango Cairo is 1.28.1

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables LIBRSVG_CFLAGS
and LIBRSVG_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
make: *** No targets specified and no makefile found.  Stop.`

Appreciate if you could kindly help me

**Comment by gojko** [comment]
as I mentioned,  librsvg-2.26.3 is the most recent version that compiles against the gdk libraries available in lambda.

**Comment by zappan** [comment]
@gojko Any chance that in the meantime the underlying AMI for lambda has changed with Node 8.10 support? If so, would it be possible to update this binary to a newer version? Thanks.

_(Tried to compile it myself on an Ubuntu based machine, failed to do so.. hoping if you have the build environment already prepared, might be quicker than setting up the whole bulid on this side.)_
