### ISSUE TITLE
ERROR Fontconfig error: Cannot load default config file

### ISSUE THREAD

**Issue by hoanhquan** [gojko/librsvg-static-lambda-binary#3]
Hi Sir. I got a error " ERROR Fontconfig error: Cannot load default config file " when try call a layer  'rsvg-convert' in my lambda function.

I had a file fonts.conf in my  root directory.

<img width="512" alt="Untitled" src="https://user-images.githubusercontent.com/4328087/61588175-17eda980-abc1-11e9-9981-528d63d1e9fc.png">

**Comment by gojko** [comment]
you need to set the fontconfig environment variables on the lambda function if you want to use fontconfig, or pass them to the shell environment when executing rsvg-convert. check out https://www.freedesktop.org/software/fontconfig/fontconfig-user.html for more information.

**Comment by hoanhquan** [comment]
Thank you. 
I had a mistake when set a variable process.env.FONTCONFIG_PATH = './';

It worked when i changed it to process.env.FONTCONFIG_PATH = __dirname;
