### ISSUE TITLE
/opt/bin/rsvg-convert: /lib64/libc.so.6: version `GLIBC_2.25' not found

### ISSUE THREAD

**Issue by ultradian** [gojko/librsvg-static-lambda-binary#4]
Hi,
I was trying to use rsvg-convert as a lambda layer, but got the following error when trying to invoke it:
```
/opt/bin/rsvg-convert: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /opt/bin/rsvg-convert)
```
I am using a Python runtime, but I assumed this shouldn't matter since I'm just directly executing the binary located at `/opt/bin/rsvg-convert`.  

I installed it by using `deploy` from the serverless repo at https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:145266761615:applications~rsvg-convert-lambda-layer
I thought this would allow me to just execute it, but clearly it is missing a library where ever it is running.  How do I make sure the right glibc is available? Do I have to rebuild it and relink and repackage it somehow?

**Comment by gojko** [comment]
the serverless app repo  version is compiled against Amazon Linux 2, and you're most likely running it under an Amazon Linux 1 instance. You'll need to rebuild it and change DOCKER_IMAGE to https://hub.docker.com/r/lambci/lambda-base

**Comment by ultradian** [comment]
You're right. All versions of Python run on Linux 1.  Bad assumption on my part.  Thanks for pointing me in the right direction, as well as putting the description of the steps in your `readme`.
